#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use App\Command\Console\{
    ArgInput,
    ConsoleOutput
};
use App\Factory\CommissionCalculatorCommandFactory;

$commands = [
    'commission-calculator' => CommissionCalculatorCommandFactory::class
];

$argInput = new ArgInput();
$argInput->setArg('param', $argv[2]);

$command = (new $commands[$argv[1]]())->create();

$command->run($argInput, new ConsoleOutput());

