FROM php:8.1-fpm

RUN apt-get update
RUN apt-get install -y libpq-dev libpng-dev curl unzip zip git

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.2.2
